version: 1.0
runtime: docker
build:
  commands:
    build:
      - echo "Building Docker image with Tesseract OCR..."
      - docker build -t arzana-app .
      - echo "Build completed"
run:
  runtime-version: 3.9
  command: gunicorn --bind 0.0.0.0:8080 --workers 2 --timeout 300 app:app
  network:
    port: 8080
    env: PORT
  env:
    - name: FLASK_ENV
      value: production
    - name: TESSERACT_CMD
      value: /usr/bin/tesseract
